apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wordpress-multi-mysql
spec:
  template:
    metadata:
      labels:
        app: wordpress-multi-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.21
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: wordpress-multi-config
              key: db_password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: wordpress-multi-config
              key: db_name
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
